#!/bin/bash
# Multi-Agent System Index and Launcher
# Quick access to all system components

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          MULTI-AGENT SYSTEM - Quick Access Index               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📚 DOCUMENTATION (Read these first):"
echo "  1. README.md              - Project overview and features"
echo "  2. USAGE_GUIDE.md         - Comprehensive usage guide"
echo "  3. QUICK_REFERENCE.md     - Quick lookup commands"
echo "  4. PROJECT_SUMMARY.md     - Project components & details"
echo "  5. FILE_MANIFEST.md       - Complete file listing"
echo ""
echo "🚀 QUICK START:"
echo "  → python3 main.py         # Run 3 complete demonstrations"
echo ""
echo "📋 RUN SPECIFIC EXAMPLES:"
echo "  → python3 -m examples.market_analysis     # Market analysis"
echo "  → python3 -m examples.product_research    # Product planning"
echo "  → python3 -m examples.workflow_demo       # Complete workflow"
echo "  → python3 -m examples.custom_agents       # Custom agents"
echo ""
echo "🔧 PROJECT STRUCTURE:"
echo "  agents/              - Core agent implementations"
echo "  ├── base.py          - Base classes & Message"
echo "  ├── research_agent.py - Information gathering"
echo "  ├── analysis_agent.py - Pattern recognition"
echo "  ├── planning_agent.py - Strategy development"
echo "  ├── execution_agent.py- Task execution"
echo "  └── coordinator.py    - Main orchestrator"
echo ""
echo "  examples/            - Working examples"
echo "  ├── market_analysis.py"
echo "  ├── product_research.py"
echo "  ├── workflow_demo.py"
echo "  └── custom_agents.py"
echo ""
echo "  utils/               - Utility modules"
echo "  ├── task_utils.py    - Task decomposition"
echo "  └── messages.py      - Message utilities"
echo ""
echo "📊 SYSTEM STATS:"
echo "  • Python Files: 16"
echo "  • Documentation Files: 5"
echo "  • Total Lines: 3,576"
echo "  • Agents: 4 default + extensible"
echo "  • Examples: 4 complete workflows"
echo ""
echo "💡 KEY FEATURES:"
echo "  ✓ Task delegation between agents"
echo "  ✓ Intelligent agent routing"
echo "  ✓ Inter-agent communication"
echo "  ✓ Result synthesis from multiple sources"
echo "  ✓ Extensible agent framework"
echo "  ✓ Zero external dependencies"
echo ""
echo "🎯 MAIN AGENTS:"
echo "  1. Research Expert       - Gathers & synthesizes data"
echo "  2. Data Analyst          - Identifies patterns & insights"
echo "  3. Strategic Planner     - Creates strategies & roadmaps"
echo "  4. Operations Manager    - Executes tasks & ensures QA"
echo ""
echo "🚀 GET STARTED:"
echo "  1. Read README.md for overview"
echo "  2. Run: python3 main.py"
echo "  3. Explore examples/ folder"
echo "  4. Check USAGE_GUIDE.md for details"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
